/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import DBconnect.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
import java.text.*;
import java.awt.print.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
/**
 *
 * @author B.A.Pavan Chamantha
 */
public class showfeedback extends javax.swing.JFrame {

       Connection con = null;
       PreparedStatement pst = null;
       ResultSet rs = null;
       int timeRun=0;
       
       public showfeedback() 
       {
            initComponents();
            con = DBconnect.connect();
        
            tableload();
            //CurrentDate();
            CurrentDate d1=new CurrentDate();
            date.setText(d1.year+"/"+d1.month+"/"+d1.day);
            
            new Thread()
            {
                public void run()
                {
                    while(timeRun==0)
                    {
            
                        Calendar cal=new GregorianCalendar();
            
                        int hour=cal.get(Calendar.HOUR);
                        if(hour==0)
                        {
                            hour=hour+12;
                        }
                        int min=cal.get(Calendar.MINUTE);
                        int sec=cal.get(Calendar.SECOND);
                        int AM_PM=cal.get(Calendar.AM_PM);
            
            
                        String day_night=""; 
                        if(AM_PM==1)
                        {
                            day_night="PM";
                        }
                        else
                        {
                            day_night="AM";
                        }
            
                        String time =hour+":"+min+":"+sec+""+day_night;
            
                        Clock.setText(time);
                    }
                }
        }.start();
    }
    
    public void tableload()
    {
        try {
            String sql = "SELECT * FROM feedback";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            FeedBackTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
 /*public void CurrentDate()
 {
    
    Calendar cal=new GregorianCalendar();
    int month=cal.get(Calendar.MONTH);
    int year=cal.get(Calendar.YEAR);
    int day=cal.get(Calendar.DAY_OF_MONTH);
    date.setText(year+"/"+(month+1)+"/"+day);
 }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FeedBackTable = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        BackButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        LogOutButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        PrintButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        disbox = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        subbox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        typebox = new javax.swing.JComboBox<String>();
        Clock = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        FeedBackTable.setBackground(new java.awt.Color(255, 204, 102));
        FeedBackTable.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        FeedBackTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Uname", "Email", "Feedback Type", "Subject", "Description"
            }
        ));
        FeedBackTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FeedBackTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(FeedBackTable);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setAlignmentY(0.5F);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(jSeparator9);

        BackButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-back-icon_1.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.setVerifyInputWhenFocusTarget(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(BackButton);
        jToolBar1.add(jSeparator3);
        jToolBar1.add(jSeparator6);

        LogOutButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LogOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout-icon.png"))); // NOI18N
        LogOutButton.setText("Log Out");
        LogOutButton.setFocusable(false);
        LogOutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogOutButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(LogOutButton);
        jToolBar1.add(jSeparator4);
        jToolBar1.add(jSeparator7);

        PrintButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PrintButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print-icon.png"))); // NOI18N
        PrintButton.setText("Print");
        PrintButton.setFocusable(false);
        PrintButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PrintButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        PrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(PrintButton);
        jToolBar1.add(jSeparator1);
        jToolBar1.add(jSeparator8);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedback-icon.png"))); // NOI18N
        jButton1.setText("Latest FeedBack");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator5);
        jToolBar1.add(jSeparator10);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Feedback details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Algerian", 1, 18), new java.awt.Color(0, 153, 0))); // NOI18N

        disbox.setColumns(20);
        disbox.setRows(5);
        jScrollPane2.setViewportView(disbox);

        jLabel3.setText("Subject");

        jLabel4.setText("Feedback Type");

        jLabel5.setText("Description");

        typebox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----------------Select----------------", "Comments", "Bug Report", "Questions" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(subbox)
                    .addComponent(typebox, 0, 296, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Clock.setFont(new java.awt.Font("DS-Digital", 1, 18)); // NOI18N
        Clock.setText("jLabel2");

        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date.setText("date");

        jMenu1.setText("Help");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help.png"))); // NOI18N
        jMenuItem2.setText("How To Do..");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Clock, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(date)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Clock)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );

        setSize(new java.awt.Dimension(767, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FeedBackTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedBackTableMouseClicked

        //Get the Selected FeedBackTable Values to Varibales
        int r= FeedBackTable.getSelectedRow();
        String Col3=FeedBackTable.getValueAt(r, 3).toString();
        String Col4=FeedBackTable.getValueAt(r, 4).toString();
        String Col5=FeedBackTable.getValueAt(r, 5).toString();
        
        //Set Field Values to the FeedBackTable Selected Values
        typebox.setSelectedItem(Col3);
        subbox.setText(Col4);
        disbox.setText(Col5);
        
    }//GEN-LAST:event_FeedBackTableMouseClicked

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed

        admin s1=new admin();
        s1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed

        MY_Home l1=new MY_Home();
        l1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void PrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintButtonActionPerformed


        Object[] options = {"FeedBack Table","A FeedBack Detail"};
        int n = JOptionPane.showOptionDialog(null,
                    "What you Want to Print?",
                    "Print Selection",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.DEFAULT_OPTION,
                    null,
                    options,
                    options[1]);  

                if(n==0) //FeedBack Table
                {  

                        MessageFormat header=new MessageFormat("FeedBack Table Report");

                        MessageFormat footer=new MessageFormat("Page{0,number,integer}");

                        try
                        {
                            FeedBackTable.print(JTable.PrintMode.NORMAL, header, footer);
                        }
                        catch(java.awt.print.PrinterException e)
                        {
                            System.err.format("Cannot print %s%n",e.getMessage());
                        }

                }
                else //if(n==1) //A FeedBack Detail
                {
                        MessageFormat header=new MessageFormat("Last FeedBack");

                        MessageFormat footer=new MessageFormat("Page{0,number,integer}");

                        try
                        {
                             String type = typebox.getSelectedItem().toString();
                             String subject = subbox.getText();
                             String discrip = disbox.getText();



                            if(type.equals("") || subject.equals("") || discrip.equals(""))     //Check for empty Field
                            {
                                JOptionPane.showMessageDialog(null,"Please Select a Feedback");   //Show the Error Message
                            }
                            else
                            {
                                        disbox.print(header,footer);
                                        
                            }
                        }
                        catch(java.awt.print.PrinterException e)
                        {
                            System.err.format("Cannot print %s%n",e.getMessage());
                        }

                }

    }//GEN-LAST:event_PrintButtonActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try
        {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"G:\\Documents\\Project\\src\\admin.pdf");
        }
        catch(Exception e)
        {
            System.out.println(e);      //Display the Exception
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //Get the Selected FeedBackTable Values to Varibales
        int t= FeedBackTable.getRowCount();                     //Count the Number of rows in the Table
        int r=t-1;                                              //Reduce 1 from the Number of rows (To Select the last Feedback)
        String Col3=FeedBackTable.getValueAt(r, 3).toString();
        String Col4=FeedBackTable.getValueAt(r, 4).toString();
        String Col5=FeedBackTable.getValueAt(r, 5).toString();
        
        //Set Field Values to the FeedBackTable Selected Values
        typebox.setSelectedItem(Col3);
        subbox.setText(Col4);
        disbox.setText(Col5);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showfeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showfeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showfeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showfeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showfeedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Clock;
    private javax.swing.JTable FeedBackTable;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton PrintButton;
    private javax.swing.JLabel date;
    private javax.swing.JTextArea disbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField subbox;
    private javax.swing.JComboBox<String> typebox;
    // End of variables declaration//GEN-END:variables
}
