/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import DBconnect.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Pubudu_Malith_Mihiran
 */
public class Sign_up extends javax.swing.JFrame {

    //Db connecting 
   Connection con = null;
   PreparedStatement pst = null;
   
   
    public Sign_up() {
        initComponents();
        
        con = DBconnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fnamebox = new javax.swing.JTextField();
        lnamebox = new javax.swing.JTextField();
        unamebox = new javax.swing.JTextField();
        learnbox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        emailbox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pwordbox = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        emsg = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        msg2 = new javax.swing.JLabel();
        msg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        jLabel1.setText("Sign up menu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 11, 139, 23));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Create you'r e-learning account ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 288, 33));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("First Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 103, 92, 28));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 108, 94, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setText("Learning year");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 165, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setText("e-Mail Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 213, -1, 28));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setText("PassWord");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 83, -1));

        fnamebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnameboxKeyReleased(evt);
            }
        });
        getContentPane().add(fnamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 104, 144, 28));

        lnamebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lnameboxKeyReleased(evt);
            }
        });
        getContentPane().add(lnamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 104, 145, 28));
        getContentPane().add(unamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 144, 28));

        learnbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----------Select----------", "First year", "Second year", "Third year", "Fourth year" }));
        learnbox.setToolTipText("");
        getContentPane().add(learnbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 159, 144, 33));

        jButton1.setFont(new java.awt.Font("Arno Pro", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));
        getContentPane().add(emailbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 214, 144, 28));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setText("UserName");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 83, -1));
        getContentPane().add(pwordbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 144, 27));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user-icon-png-16x16-214.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 250, 280));

        emsg.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(emsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 130, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home-4-xxl.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        msg2.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(msg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 130, 20));

        msg1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(msg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 130, 20));

        setSize(new java.awt.Dimension(629, 452));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
      
        //getting values in texfields 
        String fname = fnamebox.getText();
        String lname = lnamebox.getText();
        String learnyear = learnbox.getSelectedItem().toString();
        String e_mail = emailbox.getText();
        String uname = unamebox.getText();
        String pword = pwordbox.getText();
        
        //validate e-mail address is correct
        boolean status = ValidateEmail.ValidateEmail(emailbox.getText());
        if(status){
            emsg.setText("Email Valid");
        
        }
        else{
            emsg.setText("Not Valid Email");
        }
        
        if(fname.equals("") || lname.equals("") || learnyear.equals("") || e_mail.equals("") || uname.equals("") || pword.equals("")){
         JOptionPane.showMessageDialog(null, "Please Insert Signup Details");   
        }
        else{
        
        //insert signup details to the db "members"
        try {
              String q = "INSERT INTO members (First_Name , Last_Name , Learning_year , Email_Address , UserName , PassWord) Values ('"+fname+"','"+lname+"','"+learnyear+"','"+e_mail+"','"+uname+"','"+pword+"')";
        
              pst = con.prepareStatement(q);
              pst.execute();

        } 
        catch (Exception e) {
            System.out.println(e);
        }
       
        //After the submit clear the values in text filds
        fnamebox.setText("");
        lnamebox.setText("");
        learnbox.setSelectedIndex(0);
        emailbox.setText("");
        unamebox.setText("");
        pwordbox.setText("");
        
        //Display message to user user inputs are successfully submited to DB
       JOptionPane.showMessageDialog(null, "Successfully Submited your signup details");
        
        } 
        
        //After submision go back to loging page
        login g1 = new login();
        g1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        MY_Home mh = new MY_Home();
        mh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void fnameboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameboxKeyReleased
        // TODO add your handling code here:
                for(int i=0; i<fnamebox.getText().length(); i++)
        {
            if(!(Character.isLetter(fnamebox.getText().charAt(i))))
                msg1.setText("Letters only");
            else
                msg1.setText(null);
            
        }
    }//GEN-LAST:event_fnameboxKeyReleased

    private void lnameboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameboxKeyReleased
        // TODO add your handling code here:
                for(int i=0; i<lnamebox.getText().length(); i++)
        {
            if(!(Character.isLetter(lnamebox.getText().charAt(i))))
                msg2.setText("Letters only");
            else
                msg2.setText(null);
            
        }
    }//GEN-LAST:event_lnameboxKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_up().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailbox;
    private javax.swing.JLabel emsg;
    private javax.swing.JTextField fnamebox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JComboBox learnbox;
    private javax.swing.JTextField lnamebox;
    private javax.swing.JLabel msg1;
    private javax.swing.JLabel msg2;
    private javax.swing.JPasswordField pwordbox;
    private javax.swing.JTextField unamebox;
    // End of variables declaration//GEN-END:variables
}
